[[redirects]]
  from = "/proxy/*"
  to = ":splat"
  status = 200
  force = true

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"
