 [build]
  # This tells Netlify to run your script BEFORE deploying
  command = "node generate-sitemap.js"
  publish = "."

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Content-Type-Options = "nosniff"

# 1. Direct access to your SEO pages for Google
[[redirects]]
  from = "/channels_pages/*"
  to = "/channels_pages/:splat"
  status = 200

# 2. Clean URLs (e.g., /channel/9x-jalwa -> player)
[[redirects]]
  from = "/channel/:slug"
  to = "/index.html?ch=:slug"
  status = 200

# 3. Catch-all for your Single Page App (Moved to bottom)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
